---
- name: Check if libcrypto.so.4 exist
  stat:
    path: "/usr/lib/i386-linux-gnu/libcrypto.so.4"
  register: libcrypto_file

- name: Add libcrypto.so.4 file
  command: ln -s /usr/lib/i386-linux-gnu/libcrypto.so.1.1 /usr/lib/i386-linux-gnu/libcrypto.so.4
  when: libcrypto_file.stat.exists == False
