---
- name: Git clone VPCS to /tmp
  git:
    repo: https://github.com/GNS3/vpcs.git
    dest: /tmp/vpcs

- name: run mk.sh
  shell: /bin/sh mk.sh amd64
  args:
    chdir: /tmp/vpcs/src

- name: Install vpcs
  copy:
    src: /tmp/vpcs/src/vpcs
    dest: /usr/local/bin/vpcs
    mode: '0755'
    remote_src: true