---
- name: Cloner le dépôt gns3-server dans /opt
  git:
    repo: https://github.com/GNS3/gns3-server.git
    dest: /opt/gns3-server
    force: yes

- name: Installer les dépendances Python
  pip:
    requirements: /opt/gns3-server/requirements.txt

- name: Installer le package gns3-server
  pip:
    name: /opt/gns3-server/.
  tags: install-gns3

- name: Copier le fichier de service GNS3
  copy:
    src: files/gns3.service
    dest: /usr/lib/systemd/system/gns3.service
    owner: root
    group: root
    mode: 0644
  tags: test   

- name: Exécuter systemctl daemon-reload
  command: systemctl daemon-reload

- name: Démarrer le service gns3 server
  service:
    name: gns3 
    state: started