---
- name: Clone gns3-server in /opt
  git:
    repo: https://github.com/GNS3/gns3-server.git
    dest: /opt/gns3-server
    force: yes

- name: Install python dependecies
  pip:
    requirements: /opt/gns3-server/requirements.txt

- name: Install gns3-server
  pip:
    name: /opt/gns3-server/.
  tags: install-gns3

- name: Copy gns3 server systemd service
  copy:
    src: files/gns3.service
    dest: /usr/lib/systemd/system/gns3.service
    owner: root
    group: root
    mode: 0644
  tags: test   

- name: Run systemctl daemon-reload
  command: systemctl daemon-reload

- name: Run gns3
  service:
    name: gns3 
    state: started