---
- name: Clone ubridge git in /tmp
  git:
    repo: https://github.com/GNS3/ubridge.git
    dest: /tmp/ubridge

- name: run make for ubridge
  shell: make
  args:
    chdir: /tmp/ubridge/

- name: Run make install for ubridge
  shell: make install
  args:
    chdir: /tmp/ubridge/

- name: Change permission for ubridge
  file:
    path: /usr/local/bin/ubridge
    mode: u+x

- name: Copy ubridge to /usr/local/bin
  copy:
    remote_src: true
    src: /tmp/ubridge/ubridge
    dest: /usr/local/bin/ubridge
    mode: '0755'

- name: setcap ubridge
  shell: setcap cap_net_admin,cap_net_raw=ep /usr/local/bin/ubridge
