---
- name: Git clone dynamips
  git:
    repo: https://github.com/GNS3/dynamips.git
    dest: /tmp/dynamips

- name: add build folder 
  file:
    path: /tmp/dynamips/build
    state: directory

- name: Run cmake for dynamips
  command: cmake ..
  args:
    chdir: /tmp/dynamips/build

- name: Run make install for dynamips
  shell: make install
  args:
    chdir: /tmp/dynamips/build